# Generated by Django 5.1.6 on 2025-03-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_participant_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(related_name='participants', to='events.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
