# Generated by Django 5.1.6 on 2025-03-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_description_remove_participant_events_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='event',
            new_name='events',
        ),
    ]
